language: python

python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4

before_install:
  - sudo apt-get update
  - wget https://github.com/ringing-lib/ringing-lib-deb/releases/download/v0.4.0-3/libringing-dev_0.4.0-3_amd64.deb

install:
  - sudo apt-get install libreadline6 libgdome2-0
  - sudo dpkg --install libringing-dev_0.4.0-3_amd64.deb
  - pip install cython

before_script:
  - python setup.py build_ext --inplace

script:
  - python setup.py test
